{% set name = "libtvm" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/incubator-tvm/archive/v{{ version }}.tar.gz
  sha256: 0fba3822a1fef3c1ad9656527ff5bea58c1eed23e1cd262d399d777357a52b7e

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake >=3.5
    - ninja
  host:
    - dlpack >0.2
    - rang >=3.1.0
    - dmlc >=0.4
  run:
    - dlpack >0.2
    - dmlc >=0.4
    - rang >=3.1.0

test:
  commands:
    - test -d ${PREFIX}/include/tvm
    - test -f ${PREFIX}/lib/libtvm${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libtvm_runtime${SHLIB_EXT}

about:
  home: https://tvm.apache.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Open Deep Learning Compiler Stack
  description: |
    Apache TVM (incubating) is a compiler stack for deep learning systems. 
    It is designed to close the gap between the productivity-focused deep 
    learning frameworks, and the performance- and efficiency-focused hardware 
    backends. TVM works with deep learning frameworks to provide end to end 
    compilation to different backends.
  doc_url: https://tvm.apache.org/docs/
  dev_url: https://github.com/apache/incubator-tvm

extra:
  recipe-maintainers:
    - marcelotrevisani
